services:
  - type: web
    name: math-classroom-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: USE_DATABASE
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: math-classroom-db
          property: connectionString

